name: CI Build and Deploy

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  # schedule:
  #   - cron: "*/30 7-18 * * 1-5"
  #   - cron: "0 */4 * * 6,0"
  #   - cron: "0 19-23 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ics requests

      # Étape 4 : Exécuter votre script Python
      - name: Run Python script
        run: |
          python main.py 

      # Étape 5A : Si c'est une Pull Request, publier l'artefact
      - name: Upload Artifact for PR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./public 

      # Étape 5B : Si c'est un push ou un cron, déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
